const lang = {
  en: {
    name:"Yagyansh Tyagi",
    headerHome:"Home",
    headerAboutUs:"About Us",
    headerContactUs:"Contact Us",
    headerSearchPlaceholder:"Search Restaurants..",
    heroHeading: "Eat the best",
    heroLineHeading: "Explore and understand the culture more by taste...",
    locationPlaceholder: "Enter your location",
    heroButton1: "Order Food",
    heroButton2: "Make Reservation",
    heroPara: "or",
    prathamReviewName:"Pratham",
    prathamReview:"Foody is the best website..",
    resSectionSpan:"Best Rated Restaurants",
    resSectionInfo:"Order from our 1000+ food and beverages menu. Food for every taste and mood",
    resSectionButton1:"Order Food",
    aboutReviewName1:"CJ",
    aboutReview1:"Foody is the best website.",
    aboutReviewName2:"Vishal",
    aboutReview2:"Foody is the best website but i dont have money.",
    aboutReviewName3:"Pratham",
    aboutReview3:"I know Foody is the best website",
    aboutQuestion1:"What is Foody Customer Care Number?",
    aboutAnswer1:"You can reach Foodys customer care team at the following number:Customer Care Number: +91xxxxxxxxx and If you need to contact us via email, you can reach our support team at:Email: support@foody.com",
    aboutQuestion2:"Can i edit my order?",
    aboutAnswer2:"Your order can be edited before it reaches the restaurant. You could contact customer support team via chat or call to do so. Once order is placed and restaurant starts preparing your food, you may not edit its contents",
    aboutQuestion3:"I want to cancel my order",
    aboutAnswer3:"We will do our best to accommodate your request if the order is not placed to the restaurant (Customer service number:  +91xxxxxxxxx).",




  },
  हिंदी: {
    name:"यज्ञांश त्यागी",
    headerHome:"होम",
    headerAboutUs:"हमारे बारे में",
    headerContactUs:"संपर्क करें",
    headerSearchPlaceholder:"रेस्तरां खोजें.",
    heroHeading: "सबसे अच्छा खाओ",
    heroLineHeading: "स्वाद के आधार पर संस्कृति को और अधिक जानें और समझें...",
    locationPlaceholder: "अपनी स्थिति दर्ज़ करें",
    heroButton1: "भोजन का आदेश करें",
    heroButton2: "आरक्षण करें",
    heroPara: "या",
    prathamReviewName:"प्रथम",
    prathamReview:"फूडी सबसे अच्छी वेबसाइट है..",
    resSectionSpan:"सर्वश्रेष्ठ रेटेड रेस्तरां",
    resSectionInfo:"हमारे 1000+ भोजन और पेय पदार्थ मेनू से ऑर्डर करें। हर स्वाद और मूड के लिए भोजन",
    resSectionButton1:"भोजन का आदेश करें",
    aboutReviewName1:"सी जे",
    aboutReview1:"फूडी सबसे अच्छी वेबसाइट है..",
    aboutReviewName2:"विशाल",
    aboutReview2:"फूडी सबसे अच्छी वेबसाइट है लेकिन मेरे पास पैसे नहीं हैं।",
    aboutReviewName3:"प्रथम",
    aboutReview3:"मैं जानता हूं फूडी सबसे अच्छी वेबसाइट है",
    aboutQuestion1:"फूडी कस्टमर केयर नंबर क्या है?",
    aboutAnswer1:"आप Foodys ग्राहक सेवा टीम से निम्नलिखित नंबर पर संपर्क कर सकते हैं: ग्राहक सेवा नंबर: +91xxxxxxxxx और यदि आपको ईमेल के माध्यम से हमसे संपर्क करने की आवश्यकता है, तो आप हमारी सहायता टीम से यहां संपर्क कर सकते हैं: ईमेल: support@foody.com",
    aboutQuestion2:"क्या मैं अपना ऑर्डर संपादित कर सकता हूँ?",
    aboutAnswer2:"आपका ऑर्डर रेस्तरां तक ​​पहुंचने से पहले संपादित किया जा सकता है। ऐसा करने के लिए आप चैट या कॉल के माध्यम से ग्राहक सहायता टीम से संपर्क कर सकते हैं। एक बार ऑर्डर दे दिया गया और रेस्तरां आपका भोजन तैयार करना शुरू कर देता है, तो आप इसकी सामग्री को संपादित नहीं कर सकते",
    aboutQuestion3:"मैं अपना ऑर्डर रद्द करना चाहता हूं",
    aboutAnswer3:"यदि रेस्तरां को ऑर्डर नहीं दिया गया है तो हम आपके अनुरोध को समायोजित करने की पूरी कोशिश करेंगे (ग्राहक सेवा संख्या: +91xxxxxxxxx)।",
  },
};

export default lang;